eval "$(/opt/homebrew/bin/brew shellenv)"

# Created by `pipx` on 2025-07-01 15:38:25
export PATH="$PATH:/Users/tanvibhakta/.local/bin"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
